<?php
/**
 * Localized UI strings for the Languages settings tab.
 *
 * @package Breakdance_Languages
 */

declare(strict_types=1);

if (!defined('ABSPATH')) {
    exit;
}

/**
 * UI strings keyed by locale code.
 *
 * @return array<string, array{loading:string,ready:string,success:string,error:string,refresh:string}>
 */
function breakdance_languages_settings_ui_catalog(): array
{
    return [
        'en_US' => [
            'loading' => 'Applying language...',
            'loading_translations' => 'Loading translations...',
            'loading_finalizing' => 'Syncing profile...',
            'ready' => 'Language applied. Click "Refresh" to reload the page.',
            'success' => 'Language saved successfully.',
            'error' => 'Could not save the selected language.',
            'session_expired' => 'Your session has expired. Reload this page and try again.',
            'refresh' => 'Refresh',
            'tab_title' => 'Languages',
            'page_description' => 'Choose the language used in the Breakdance Builder interface, element names, and first-party controls.',
            'builder_language_label' => 'Builder language',
            'header_alt' => 'Builder Language',
            'license_notice' => 'Activate a valid license to use Builder Languages for Breakdance translations.',
            'license_heading' => 'License',
            'license_status' => 'Status',
            'license_account' => 'Account',
            'license_status_dev' => 'Development mode',
            'license_status_active' => 'Active',
            'license_status_inactive' => 'Inactive',
            'license_dev_description' => 'Development build. All translations are unlocked in this environment.',
            'license_inactive_description' => 'Activate your license to load Breakdance Builder translations.',
            'license_active_description' => 'Your license is active. All included translations are available.',
            'license_manage' => 'Manage license',
            'license_buy' => 'Buy license',
            'license_environment' => 'Environment',
            'license_environment_sandbox' => 'Sandbox (Freemius)',
            'license_environment_production' => 'Production',
            'license_environment_dev' => 'Local development',
            'profile_language_heading' => 'WordPress profile language',
            'profile_language_current' => 'Your profile is set to: %s',
            'profile_language_auto_hint' => 'With “Use WordPress profile language” selected, the builder follows the language in Users → Profile → Language. Change it there to switch the builder language.',
            'profile_language_align_hint' => 'When you pick a specific builder language, this plugin also updates your WordPress profile language to match.',
            'profile_language_mismatch' => 'Your WordPress profile is set to %1$s, but the builder language is %2$s. Align both to the same language.',
            'profile_language_edit' => 'Edit profile language',
            'profile_language_refresh_hint' => 'If Users → Profile still shows the old language, reload that page after saving here.',
            'wp_language_pack_missing' => 'The WordPress admin language pack for %s is not installed yet. Install it to translate Users → Profile and other admin screens.',
            'wp_language_pack_installed' => 'WordPress language pack installed for %s.',
            'wp_language_pack_install_button' => 'Install WordPress language pack',
            'wp_language_pack_installing' => 'Installing WordPress language pack...',
            'wp_language_pack_downloading' => 'Downloading translation files...',
            'wp_language_pack_finalizing' => 'Finalizing installation...',
            'wp_language_pack_installed_short' => 'Installation complete.',
            'wp_language_pack_install_error' => 'Could not install the WordPress language pack. Check your connection or install it manually under Dashboard → Updates → Translations.',
            'wp_language_pack_manual_hint' => 'Ask an administrator to install the language under Dashboard → Updates → Translations, or Users → Profile → Language.',
            'wp_language_pack_reload' => 'Refresh page',
            'wp_language_pack_reload_hint' => 'Click “Refresh page” to apply the WordPress admin language.',
        ],
        'en_GB' => [
            'loading' => 'Applying language...',
            'loading_translations' => 'Loading translations...',
            'loading_finalizing' => 'Syncing profile...',
            'ready' => 'Language applied. Click "Refresh" to reload the page.',
            'success' => 'Language saved successfully.',
            'error' => 'Could not save the selected language.',
            'session_expired' => 'Your session has expired. Reload this page and try again.',
            'refresh' => 'Refresh',
            'tab_title' => 'Languages',
            'page_description' => 'Choose the language used in the Breakdance Builder interface, element names, and first-party controls.',
            'builder_language_label' => 'Builder language',
            'header_alt' => 'Builder Language',
            'license_notice' => 'Activate a valid licence to use Builder Languages for Breakdance translations.',
            'license_heading' => 'Licence',
            'license_status' => 'Status',
            'license_account' => 'Account',
            'license_status_dev' => 'Development mode',
            'license_status_active' => 'Active',
            'license_status_inactive' => 'Inactive',
            'license_dev_description' => 'Development build. All translations are unlocked in this environment.',
            'license_inactive_description' => 'Activate your licence to load Breakdance Builder translations.',
            'license_active_description' => 'Your licence is active. All included translations are available.',
            'license_manage' => 'Manage licence',
            'license_buy' => 'Buy licence',
            'license_environment' => 'Environment',
            'license_environment_sandbox' => 'Sandbox (Freemius)',
            'license_environment_production' => 'Production',
            'license_environment_dev' => 'Local development',
            'profile_language_heading' => 'WordPress profile language',
            'profile_language_current' => 'Your profile is set to: %s',
            'profile_language_auto_hint' => 'With “Use WordPress profile language” selected, the builder follows the language in Users → Profile → Language. Change it there to switch the builder language.',
            'profile_language_align_hint' => 'When you pick a specific builder language, this plugin also updates your WordPress profile language to match.',
            'profile_language_mismatch' => 'Your WordPress profile is set to %1$s, but the builder language is %2$s. Align both to the same language.',
            'profile_language_edit' => 'Edit profile language',
            'profile_language_refresh_hint' => 'If Users → Profile still shows the old language, reload that page after saving here.',
            'wp_language_pack_missing' => 'The WordPress admin language pack for %s is not installed yet. Install it to translate Users → Profile and other admin screens.',
            'wp_language_pack_installed' => 'WordPress language pack installed for %s.',
            'wp_language_pack_install_button' => 'Install WordPress language pack',
            'wp_language_pack_installing' => 'Installing WordPress language pack...',
            'wp_language_pack_downloading' => 'Downloading translation files...',
            'wp_language_pack_finalizing' => 'Finalizing installation...',
            'wp_language_pack_installed_short' => 'Installation complete.',
            'wp_language_pack_install_error' => 'Could not install the WordPress language pack. Check your connection or install it manually under Dashboard → Updates → Translations.',
            'wp_language_pack_manual_hint' => 'Ask an administrator to install the language under Dashboard → Updates → Translations, or Users → Profile → Language.',
        ],
        'pt_BR' => [
            'loading' => 'Aplicando idioma...',
            'loading_translations' => 'Carregando traduções...',
            'loading_finalizing' => 'Sincronizando perfil...',
            'ready' => 'Idioma aplicado. Clique em "Atualizar" para recarregar a página.',
            'success' => 'Idioma salvo com sucesso.',
            'error' => 'Não foi possível salvar o idioma selecionado.',
            'session_expired' => 'Sua sessão expirou. Recarregue esta página e tente novamente.',
            'refresh' => 'Atualizar',
            'tab_title' => 'Idiomas',
            'page_description' => 'Escolha o idioma usado na interface do Breakdance Builder, nos nomes dos elementos e nos controles nativos.',
            'builder_language_label' => 'Idioma do builder',
            'header_alt' => 'Idioma do Builder',
            'license_notice' => 'Ative uma licença válida para usar as traduções do Builder Languages for Breakdance.',
            'license_heading' => 'Licença',
            'license_status' => 'Status',
            'license_account' => 'Conta',
            'license_status_dev' => 'Modo de desenvolvimento',
            'license_status_active' => 'Ativa',
            'license_status_inactive' => 'Inativa',
            'license_dev_description' => 'Build de desenvolvimento. Todas as traduções estão liberadas neste ambiente.',
            'license_inactive_description' => 'Ative sua licença para carregar as traduções do Breakdance Builder.',
            'license_active_description' => 'Sua licença está ativa. Todas as traduções incluídas estão disponíveis.',
            'license_manage' => 'Gerenciar licença',
            'license_buy' => 'Comprar licença',
            'license_environment' => 'Ambiente',
            'license_environment_sandbox' => 'Sandbox (Freemius)',
            'license_environment_production' => 'Produção',
            'license_environment_dev' => 'Desenvolvimento local',
            'profile_language_heading' => 'Idioma do perfil WordPress',
            'profile_language_current' => 'Seu perfil está em: %s',
            'profile_language_auto_hint' => 'Com “Usar idioma do perfil do WordPress” selecionado, o builder segue o idioma em Usuários → Perfil → Idioma. Altere lá para mudar o idioma do builder.',
            'profile_language_align_hint' => 'Ao escolher um idioma específico do builder, o plugin também atualiza o idioma do seu perfil WordPress para corresponder.',
            'profile_language_mismatch' => 'Seu perfil WordPress está em %1$s, mas o idioma do builder é %2$s. Alinhe os dois para o mesmo idioma.',
            'profile_language_edit' => 'Editar idioma do perfil',
            'profile_language_refresh_hint' => 'Se Usuários → Perfil ainda mostrar o idioma antigo, recarregue essa página depois de salvar aqui.',
            'wp_language_pack_missing' => 'O pacote de idioma do WordPress para %s ainda não está instalado. Instale-o para traduzir Usuários → Perfil e outras telas do admin.',
            'wp_language_pack_installed' => 'Pacote de idioma do WordPress instalado para %s.',
            'wp_language_pack_install_button' => 'Instalar idioma do WordPress',
            'wp_language_pack_installing' => 'Instalando idioma do WordPress...',
            'wp_language_pack_downloading' => 'Baixando arquivos de tradução...',
            'wp_language_pack_finalizing' => 'Finalizando instalação...',
            'wp_language_pack_installed_short' => 'Instalação concluída.',
            'wp_language_pack_install_error' => 'Não foi possível instalar o pacote de idioma do WordPress. Verifique a conexão ou instale manualmente em Painel → Atualizações → Traduções.',
            'wp_language_pack_manual_hint' => 'Peça a um administrador para instalar o idioma em Painel → Atualizações → Traduções, ou em Usuários → Perfil → Idioma.',
            'wp_language_pack_reload' => 'Atualizar página',
            'wp_language_pack_reload_hint' => 'Clique em “Atualizar página” para aplicar o idioma do admin WordPress.',
        ],
        'pt_PT' => [
            'loading' => 'A aplicar idioma...',
            'ready' => 'Idioma aplicado. Clique em "Atualizar" para recarregar a página.',
            'success' => 'Idioma guardado com sucesso.',
            'error' => 'Não foi possível guardar o idioma selecionado.',
            'refresh' => 'Atualizar',
            'tab_title' => 'Idiomas',
            'page_description' => 'Escolha o idioma usado na interface do Breakdance Builder, nos nomes dos elementos e nos controlos nativos.',
            'builder_language_label' => 'Idioma do builder',
            'header_alt' => 'Idioma do Builder',
            'license_notice' => 'Ative uma licença válida para usar as traduções do Builder Languages for Breakdance.',
            'license_heading' => 'Licença',
            'license_status' => 'Estado',
            'license_account' => 'Conta',
            'license_status_dev' => 'Modo de desenvolvimento',
            'license_status_active' => 'Ativa',
            'license_status_inactive' => 'Inativa',
            'license_dev_description' => 'Build de desenvolvimento. Todas as traduções estão disponíveis neste ambiente.',
            'license_inactive_description' => 'Ative a sua licença para carregar as traduções do Breakdance Builder.',
            'license_active_description' => 'A sua licença está ativa. Todas as traduções incluídas estão disponíveis.',
            'license_manage' => 'Gerir licença',
            'license_buy' => 'Comprar licença',
            'license_environment' => 'Ambiente',
            'license_environment_sandbox' => 'Sandbox (Freemius)',
            'license_environment_production' => 'Produção',
            'license_environment_dev' => 'Desenvolvimento local',
            'profile_language_heading' => 'Idioma do perfil WordPress',
            'profile_language_current' => 'O seu perfil está em: %s',
            'profile_language_auto_hint' => 'Com “Usar idioma do perfil do WordPress” selecionado, o builder segue o idioma em Utilizadores → Perfil → Idioma. Altere lá para mudar o idioma do builder.',
            'profile_language_align_hint' => 'Ao escolher um idioma específico do builder, o plugin também atualiza o idioma do seu perfil WordPress para corresponder.',
            'profile_language_mismatch' => 'O seu perfil WordPress está em %1$s, mas o idioma do builder é %2$s. Alinhe ambos para o mesmo idioma.',
            'profile_language_edit' => 'Editar idioma do perfil',
            'wp_language_pack_missing' => 'O pacote de idioma do WordPress para %s ainda não está instalado. Instale-o para traduzir Utilizadores → Perfil e outros ecrãs do admin.',
            'wp_language_pack_installed' => 'Pacote de idioma do WordPress instalado para %s.',
            'wp_language_pack_install_button' => 'Instalar idioma do WordPress',
            'wp_language_pack_installing' => 'A instalar idioma do WordPress...',
            'wp_language_pack_install_error' => 'Não foi possível instalar o pacote de idioma do WordPress. Verifique a ligação ou instale manualmente em Painel → Atualizações → Traduções.',
            'wp_language_pack_manual_hint' => 'Peça a um administrador para instalar o idioma em Painel → Atualizações → Traduções, ou em Utilizadores → Perfil → Idioma.',
            'wp_language_pack_reload' => 'Atualizar página',
            'wp_language_pack_reload_hint' => 'Clique em “Atualizar página” para aplicar o idioma do admin WordPress.',
        ],
        'fr_FR' => [
            'loading' => 'Application de la langue...',
            'ready' => 'Langue appliquée. Cliquez sur "Actualiser" pour recharger la page.',
            'success' => 'Langue enregistrée avec succès.',
            'error' => 'Impossible d’enregistrer la langue sélectionnée.',
            'refresh' => 'Actualiser',
            'tab_title' => 'Langues',
            'page_description' => 'Choisissez la langue utilisée dans l’interface du Breakdance Builder, les noms des éléments et les contrôles natifs.',
            'builder_language_label' => 'Langue du builder',
            'header_alt' => 'Langue du Builder',
            'license_notice' => 'Activez une licence valide pour utiliser les traductions Builder Languages for Breakdance.',
            'license_heading' => 'Licence',
            'license_status' => 'Statut',
            'license_account' => 'Compte',
            'license_status_dev' => 'Mode développement',
            'license_status_active' => 'Active',
            'license_status_inactive' => 'Inactive',
            'license_dev_description' => 'Build de développement. Toutes les traductions sont débloquées dans cet environnement.',
            'license_inactive_description' => 'Activez votre licence pour charger les traductions du Breakdance Builder.',
            'license_active_description' => 'Votre licence est active. Toutes les traductions incluses sont disponibles.',
            'license_manage' => 'Gérer la licence',
            'license_buy' => 'Acheter une licence',
            'license_environment' => 'Environnement',
            'license_environment_sandbox' => 'Sandbox (Freemius)',
            'license_environment_production' => 'Production',
            'license_environment_dev' => 'Développement local',
            'profile_language_heading' => 'Langue du profil WordPress',
            'profile_language_current' => 'Votre profil est défini sur : %s',
            'profile_language_auto_hint' => 'Avec « Utiliser la langue du profil WordPress », le builder suit la langue dans Utilisateurs → Profil → Langue.',
            'profile_language_align_hint' => 'Lorsque vous choisissez une langue précise du builder, le plugin met aussi à jour la langue de votre profil WordPress.',
            'profile_language_mismatch' => 'Votre profil WordPress est en %1$s, mais la langue du builder est %2$s. Alignez les deux sur la même langue.',
            'profile_language_edit' => 'Modifier la langue du profil',
            'wp_language_pack_missing' => 'Le pack de langue WordPress pour %s n’est pas encore installé. Installez-le pour traduire Utilisateurs → Profil et les autres écrans d’administration.',
            'wp_language_pack_installed' => 'Pack de langue WordPress installé pour %s.',
            'wp_language_pack_install_button' => 'Installer la langue WordPress',
            'wp_language_pack_installing' => 'Installation de la langue WordPress...',
            'wp_language_pack_install_error' => 'Impossible d’installer le pack de langue WordPress. Vérifiez la connexion ou installez-le manuellement dans Tableau de bord → Mises à jour → Traductions.',
            'wp_language_pack_manual_hint' => 'Demandez à un administrateur d’installer la langue dans Tableau de bord → Mises à jour → Traductions, ou Utilisateurs → Profil → Langue.',
        ],
        'de_DE' => [
            'loading' => 'Sprache wird angewendet...',
            'ready' => 'Sprache angewendet. Klicken Sie auf "Aktualisieren", um die Seite neu zu laden.',
            'success' => 'Sprache erfolgreich gespeichert.',
            'error' => 'Die ausgewählte Sprache konnte nicht gespeichert werden.',
            'refresh' => 'Aktualisieren',
            'tab_title' => 'Sprachen',
            'page_description' => 'Wählen Sie die Sprache für die Breakdance-Builder-Oberfläche, Elementnamen und native Steuerelemente.',
            'builder_language_label' => 'Builder-Sprache',
            'header_alt' => 'Builder-Sprache',
            'license_notice' => 'Aktivieren Sie eine gültige Lizenz, um die Builder Languages for Breakdance-Übersetzungen zu nutzen.',
            'license_heading' => 'Lizenz',
            'license_status' => 'Status',
            'license_account' => 'Konto',
            'license_status_dev' => 'Entwicklungsmodus',
            'license_status_active' => 'Aktiv',
            'license_status_inactive' => 'Inaktiv',
            'license_dev_description' => 'Entwicklungsbuild. Alle Übersetzungen sind in dieser Umgebung freigeschaltet.',
            'license_inactive_description' => 'Aktivieren Sie Ihre Lizenz, um die Breakdance-Builder-Übersetzungen zu laden.',
            'license_active_description' => 'Ihre Lizenz ist aktiv. Alle enthaltenen Übersetzungen sind verfügbar.',
            'license_manage' => 'Lizenz verwalten',
            'license_buy' => 'Lizenz kaufen',
            'license_environment' => 'Umgebung',
            'license_environment_sandbox' => 'Sandbox (Freemius)',
            'license_environment_production' => 'Produktion',
            'license_environment_dev' => 'Lokale Entwicklung',
            'profile_language_heading' => 'WordPress-Profilsprache',
            'profile_language_current' => 'Ihr Profil ist auf folgende Sprache eingestellt: %s',
            'profile_language_auto_hint' => 'Bei „WordPress-Profilsprache verwenden“ folgt der Builder der Sprache unter Benutzer → Profil → Sprache.',
            'profile_language_align_hint' => 'Wenn Sie eine bestimmte Builder-Sprache wählen, aktualisiert das Plugin auch die WordPress-Profilsprache.',
            'profile_language_mismatch' => 'Ihr WordPress-Profil ist auf %1$s eingestellt, die Builder-Sprache ist jedoch %2$s. Stellen Sie beide auf dieselbe Sprache ein.',
            'profile_language_edit' => 'Profilsprache bearbeiten',
            'wp_language_pack_missing' => 'Das WordPress-Sprachpaket für %s ist noch nicht installiert. Installieren Sie es, um Benutzer → Profil und andere Admin-Bereiche zu übersetzen.',
            'wp_language_pack_installed' => 'WordPress-Sprachpaket für %s installiert.',
            'wp_language_pack_install_button' => 'WordPress-Sprachpaket installieren',
            'wp_language_pack_installing' => 'WordPress-Sprachpaket wird installiert...',
            'wp_language_pack_downloading' => 'Übersetzungsdateien werden heruntergeladen...',
            'wp_language_pack_finalizing' => 'Installation wird abgeschlossen...',
            'wp_language_pack_installed_short' => 'Installation abgeschlossen.',
            'wp_language_pack_install_error' => 'Das WordPress-Sprachpaket konnte nicht installiert werden. Prüfen Sie die Verbindung oder installieren Sie es manuell unter Dashboard → Updates → Übersetzungen.',
            'wp_language_pack_manual_hint' => 'Bitten Sie einen Administrator, die Sprache unter Dashboard → Updates → Übersetzungen oder Benutzer → Profil → Sprache zu installieren.',
        ],
        'es_ES' => [
            'loading' => 'Aplicando idioma...',
            'ready' => 'Idioma aplicado. Haz clic en "Actualizar" para recargar la página.',
            'success' => 'Idioma guardado correctamente.',
            'error' => 'No se pudo guardar el idioma seleccionado.',
            'refresh' => 'Actualizar',
            'tab_title' => 'Idiomas',
            'page_description' => 'Elige el idioma usado en la interfaz del Breakdance Builder, los nombres de los elementos y los controles nativos.',
            'builder_language_label' => 'Idioma del builder',
            'header_alt' => 'Idioma del Builder',
            'license_notice' => 'Activa una licencia válida para usar las traducciones de Builder Languages for Breakdance.',
            'license_heading' => 'Licencia',
            'license_status' => 'Estado',
            'license_account' => 'Cuenta',
            'license_status_dev' => 'Modo de desarrollo',
            'license_status_active' => 'Activa',
            'license_status_inactive' => 'Inactiva',
            'license_dev_description' => 'Build de desarrollo. Todas las traducciones están desbloqueadas en este entorno.',
            'license_inactive_description' => 'Activa tu licencia para cargar las traducciones del Breakdance Builder.',
            'license_active_description' => 'Tu licencia está activa. Todas las traducciones incluidas están disponibles.',
            'license_manage' => 'Gestionar licencia',
            'license_buy' => 'Comprar licencia',
            'license_environment' => 'Entorno',
            'license_environment_sandbox' => 'Sandbox (Freemius)',
            'license_environment_production' => 'Producción',
            'license_environment_dev' => 'Desarrollo local',
            'profile_language_heading' => 'Idioma del perfil de WordPress',
            'profile_language_current' => 'Tu perfil está en: %s',
            'profile_language_auto_hint' => 'Con «Usar idioma del perfil de WordPress», el builder sigue el idioma en Usuarios → Perfil → Idioma.',
            'profile_language_align_hint' => 'Al elegir un idioma específico del builder, el plugin también actualiza el idioma de tu perfil de WordPress.',
            'profile_language_mismatch' => 'Tu perfil de WordPress está en %1$s, pero el idioma del builder es %2$s. Alinea ambos al mismo idioma.',
            'profile_language_edit' => 'Editar idioma del perfil',
            'wp_language_pack_missing' => 'El paquete de idioma de WordPress para %s aún no está instalado. Instálalo para traducir Usuarios → Perfil y otras pantallas del admin.',
            'wp_language_pack_installed' => 'Paquete de idioma de WordPress instalado para %s.',
            'wp_language_pack_install_button' => 'Instalar idioma de WordPress',
            'wp_language_pack_installing' => 'Instalando idioma de WordPress...',
            'wp_language_pack_install_error' => 'No se pudo instalar el paquete de idioma de WordPress. Comprueba la conexión o instálalo manualmente en Escritorio → Actualizaciones → Traducciones.',
            'wp_language_pack_manual_hint' => 'Pide a un administrador que instale el idioma en Escritorio → Actualizaciones → Traducciones, o en Usuarios → Perfil → Idioma.',
        ],
        'it_IT' => [
            'loading' => 'Applicazione della lingua...',
            'loading_translations' => 'Caricamento traduzioni...',
            'loading_finalizing' => 'Sincronizzazione profilo...',
            'ready' => 'Lingua applicata. Fai clic su "Aggiorna" per ricaricare la pagina.',
            'success' => 'Lingua salvata correttamente.',
            'error' => 'Impossibile salvare la lingua selezionata.',
            'session_expired' => 'La sessione è scaduta. Ricarica questa pagina e riprova.',
            'refresh' => 'Aggiorna',
            'tab_title' => 'Lingue',
            'page_description' => 'Scegli la lingua usata nell\'interfaccia di Breakdance Builder, nei nomi degli elementi e nei controlli nativi.',
            'builder_language_label' => 'Lingua del builder',
            'header_alt' => 'Lingua del Builder',
            'license_notice' => 'Attiva una licenza valida per usare le traduzioni di Builder Languages for Breakdance.',
            'license_heading' => 'Licenza',
            'license_status' => 'Stato',
            'license_account' => 'Account',
            'license_status_dev' => 'Modalità sviluppo',
            'license_status_active' => 'Attiva',
            'license_status_inactive' => 'Inattiva',
            'license_dev_description' => 'Build di sviluppo. Tutte le traduzioni sono sbloccate in questo ambiente.',
            'license_inactive_description' => 'Attiva la licenza per caricare le traduzioni di Breakdance Builder.',
            'license_active_description' => 'La tua licenza è attiva. Tutte le traduzioni incluse sono disponibili.',
            'license_manage' => 'Gestisci licenza',
            'license_buy' => 'Acquista licenza',
            'license_environment' => 'Ambiente',
            'license_environment_sandbox' => 'Sandbox (Freemius)',
            'license_environment_production' => 'Produzione',
            'license_environment_dev' => 'Sviluppo locale',
            'profile_language_heading' => 'Lingua del profilo WordPress',
            'profile_language_current' => 'Il tuo profilo è impostato su: %s',
            'profile_language_auto_hint' => 'Con "Usa la lingua del profilo WordPress", il builder segue la lingua in Utenti → Profilo → Lingua.',
            'profile_language_align_hint' => 'Quando scegli una lingua specifica del builder, il plugin aggiorna anche la lingua del profilo WordPress.',
            'profile_language_mismatch' => 'Il profilo WordPress è impostato su %1$s, ma la lingua del builder è %2$s. Allinea entrambi alla stessa lingua.',
            'profile_language_edit' => 'Modifica lingua del profilo',
            'profile_language_refresh_hint' => 'Se Utenti → Profilo mostra ancora la vecchia lingua, ricarica quella pagina dopo il salvataggio qui.',
            'wp_language_pack_missing' => 'Il pacchetto lingua di WordPress per %s non è ancora installato. Installalo per tradurre Utenti → Profilo e altre schermate admin.',
            'wp_language_pack_installed' => 'Pacchetto lingua WordPress installato per %s.',
            'wp_language_pack_install_button' => 'Installa pacchetto lingua WordPress',
            'wp_language_pack_installing' => 'Installazione pacchetto lingua WordPress...',
            'wp_language_pack_downloading' => 'Download file di traduzione...',
            'wp_language_pack_finalizing' => 'Finalizzazione installazione...',
            'wp_language_pack_installed_short' => 'Installazione completata.',
            'wp_language_pack_install_error' => 'Impossibile installare il pacchetto lingua WordPress. Controlla la connessione o installalo manualmente da Bacheca → Aggiornamenti → Traduzioni.',
            'wp_language_pack_manual_hint' => 'Chiedi a un amministratore di installare la lingua da Bacheca → Aggiornamenti → Traduzioni, o da Utenti → Profilo → Lingua.',
            'wp_language_pack_reload' => 'Aggiorna pagina',
            'wp_language_pack_reload_hint' => 'Fai clic su “Aggiorna pagina” per applicare la lingua dell’admin WordPress.',
        ],
        'ar' => [
            'loading' => 'جارٍ تطبيق اللغة...',
            'ready' => 'تم تطبيق اللغة. انقر على "تحديث" لإعادة تحميل الصفحة.',
            'success' => 'تم حفظ اللغة بنجاح.',
            'error' => 'تعذر حفظ اللغة المحددة.',
            'refresh' => 'تحديث',
            'tab_title' => 'اللغات',
            'page_description' => 'اختر اللغة المستخدمة في واجهة Breakdance Builder وأسماء العناصر والعناصر التحكم الأصلية.',
            'builder_language_label' => 'لغة البناء',
            'header_alt' => 'لغة البناء',
            'license_notice' => 'فعّل ترخيصًا صالحًا لاستخدام ترجمات Builder Languages for Breakdance.',
            'license_heading' => 'الترخيص',
            'license_status' => 'الحالة',
            'license_account' => 'الحساب',
            'license_status_dev' => 'وضع التطوير',
            'license_status_active' => 'نشط',
            'license_status_inactive' => 'غير نشط',
            'license_dev_description' => 'إصدار تطوير. جميع الترجمات متاحة في هذه البيئة.',
            'license_inactive_description' => 'فعّل ترخيصك لتحميل ترجمات Breakdance Builder.',
            'license_active_description' => 'ترخيصك نشط. جميع الترجمات المضمنة متاحة.',
            'license_manage' => 'إدارة الترخيص',
            'license_buy' => 'شراء ترخيص',
            'license_environment' => 'البيئة',
            'license_environment_sandbox' => 'Sandbox (Freemius)',
            'license_environment_production' => 'الإنتاج',
            'license_environment_dev' => 'تطوير محلي',
            'profile_language_heading' => 'لغة ملف WordPress الشخصي',
            'profile_language_current' => 'ملفك الشخصي مضبوط على: %s',
            'profile_language_auto_hint' => 'عند اختيار «استخدام لغة ملف WordPress الشخصي»، يتبع البناء لغة المستخدمين → الملف الشخصي → اللغة.',
            'profile_language_align_hint' => 'عند اختيار لغة محددة للبناء، يحدّث المكوّن أيضًا لغة ملف WordPress الشخصي لتطابقها.',
            'profile_language_mismatch' => 'ملف WordPress الشخصي مضبوط على %1$s، لكن لغة البناء هي %2$s. اجعلهما بنفس اللغة.',
            'profile_language_edit' => 'تعديل لغة الملف الشخصي',
            'wp_language_pack_missing' => 'حزمة لغة WordPress لـ %s غير مثبتة بعد. ثبّتها لترجمة المستخدمون → الملف الشخصي وشاشات الإدارة الأخرى.',
            'wp_language_pack_installed' => 'تم تثبيت حزمة لغة WordPress لـ %s.',
            'wp_language_pack_install_button' => 'تثبيت لغة WordPress',
            'wp_language_pack_installing' => 'جارٍ تثبيت لغة WordPress...',
            'wp_language_pack_install_error' => 'تعذر تثبيت حزمة لغة WordPress. تحقق من الاتصال أو ثبّتها يدويًا من لوحة التحكم → التحديثات → الترجمات.',
            'wp_language_pack_manual_hint' => 'اطلب من المسؤول تثبيت اللغة من لوحة التحكم → التحديثات → الترجمات، أو المستخدمون → الملف الشخصي → اللغة.',
        ],
        'ja_JP' => [
            'loading' => '言語を適用しています...',
            'ready' => '言語を適用しました。「更新」をクリックしてページを再読み込みしてください。',
            'success' => '言語を保存しました。',
            'error' => '選択した言語を保存できませんでした。',
            'refresh' => '更新',
            'tab_title' => '言語',
            'page_description' => 'Breakdance Builder のインターフェース、要素名、ネイティブコントロールで使用する言語を選択してください。',
            'builder_language_label' => 'ビルダー言語',
            'header_alt' => 'ビルダー言語',
            'license_notice' => 'Builder Languages for Breakdance の翻訳を使用するには、有効なライセンスを有効化してください。',
            'license_heading' => 'ライセンス',
            'license_status' => 'ステータス',
            'license_account' => 'アカウント',
            'license_status_dev' => '開発モード',
            'license_status_active' => '有効',
            'license_status_inactive' => '無効',
            'license_dev_description' => '開発ビルドです。この環境ではすべての翻訳が利用できます。',
            'license_inactive_description' => 'ライセンスを有効化して Breakdance Builder の翻訳を読み込んでください。',
            'license_active_description' => 'ライセンスは有効です。含まれるすべての翻訳が利用できます。',
            'license_manage' => 'ライセンスを管理',
            'license_buy' => 'ライセンスを購入',
            'license_environment' => '環境',
            'license_environment_sandbox' => 'Sandbox (Freemius)',
            'license_environment_production' => '本番',
            'license_environment_dev' => 'ローカル開発',
            'profile_language_heading' => 'WordPressプロフィールの言語',
            'profile_language_current' => 'プロフィールの言語: %s',
            'profile_language_auto_hint' => '「WordPressプロフィールの言語を使用」を選ぶと、ビルダーはユーザー → プロフィール → 言語の設定に従います。',
            'profile_language_align_hint' => '特定のビルダー言語を選ぶと、WordPressプロフィールの言語も同じ言語に更新されます。',
            'profile_language_mismatch' => 'WordPressプロフィールは %1$s ですが、ビルダー言語は %2$s です。同じ言語に揃えてください。',
            'profile_language_edit' => 'プロフィールの言語を編集',
            'wp_language_pack_missing' => 'WordPress の %s 言語パックがまだインストールされていません。ユーザー → プロフィールなどの管理画面を翻訳するにはインストールしてください。',
            'wp_language_pack_installed' => 'WordPress 言語パック（%s）をインストールしました。',
            'wp_language_pack_install_button' => 'WordPress 言語パックをインストール',
            'wp_language_pack_installing' => 'WordPress 言語パックをインストールしています...',
            'wp_language_pack_install_error' => 'WordPress 言語パックをインストールできませんでした。接続を確認するか、ダッシュボード → 更新 → 翻訳から手動でインストールしてください。',
            'wp_language_pack_manual_hint' => '管理者に、ダッシュボード → 更新 → 翻訳、またはユーザー → プロフィール → 言語からインストールするよう依頼してください。',
        ],
    ];
}

/**
 * Language names for the settings dropdown, keyed by UI locale.
 *
 * @return array<string, array<string, string>>
 */
function breakdance_languages_locale_labels_catalog(): array
{
    return [
        'en_US' => [
            'auto' => 'Use WordPress profile language',
            'pt_BR' => 'Portuguese (Brazil)',
            'pt_PT' => 'Portuguese',
            'fr_FR' => 'French',
            'de_DE' => 'German',
            'es_ES' => 'Spanish',
            'ar' => 'Arabic',
            'ja_JP' => 'Japanese',
            'it_IT' => 'Italian',
            'en_GB' => 'English (International)',
            'en_US' => 'English (United States)',
        ],
        'en_GB' => [
            'auto' => 'Use WordPress profile language',
            'pt_BR' => 'Portuguese (Brazil)',
            'pt_PT' => 'Portuguese',
            'fr_FR' => 'French',
            'de_DE' => 'German',
            'es_ES' => 'Spanish',
            'ar' => 'Arabic',
            'ja_JP' => 'Japanese',
            'it_IT' => 'Italian',
            'en_GB' => 'English (International)',
            'en_US' => 'English (United States)',
        ],
        'pt_BR' => [
            'auto' => 'Usar idioma do perfil do WordPress',
            'pt_BR' => 'Português (Brasil)',
            'pt_PT' => 'Português',
            'fr_FR' => 'Francês',
            'de_DE' => 'Alemão',
            'es_ES' => 'Espanhol',
            'es_LA' => 'Espanhol (América Latina)',
            'ar' => 'Árabe',
            'ja_JP' => 'Japonês',
            'it_IT' => 'Italiano',
            'nl_NL' => 'Holandês',
            'hi_IN' => 'Hindi',
            'ru_RU' => 'Russo',
            'zh_CN' => 'Chinês (Simplificado)',
            'ko_KR' => 'Coreano',
            'pl_PL' => 'Polonês',
            'he_IL' => 'Hebraico',
            'en_GB' => 'Inglês (Internacional)',
            'en_US' => 'Inglês (Estados Unidos)',
        ],
        'pt_PT' => [
            'auto' => 'Usar idioma do perfil do WordPress',
            'pt_BR' => 'Português (Brasil)',
            'pt_PT' => 'Português',
            'fr_FR' => 'Francês',
            'de_DE' => 'Alemão',
            'es_ES' => 'Espanhol',
            'ar' => 'Árabe',
            'ja_JP' => 'Japonês',
            'it_IT' => 'Italiano',
            'en_GB' => 'Inglês (Internacional)',
            'en_US' => 'Inglês (Estados Unidos)',
        ],
        'fr_FR' => [
            'auto' => 'Utiliser la langue du profil WordPress',
            'pt_BR' => 'Portugais (Brésil)',
            'pt_PT' => 'Portugais',
            'fr_FR' => 'Français',
            'de_DE' => 'Allemand',
            'es_ES' => 'Espagnol',
            'ar' => 'Arabe',
            'ja_JP' => 'Japonais',
            'it_IT' => 'Italien',
            'en_GB' => 'Anglais (International)',
            'en_US' => 'Anglais (États-Unis)',
        ],
        'de_DE' => [
            'auto' => 'WordPress-Profilsprache verwenden',
            'pt_BR' => 'Portugiesisch (Brasilien)',
            'pt_PT' => 'Portugiesisch',
            'fr_FR' => 'Französisch',
            'de_DE' => 'Deutsch',
            'es_ES' => 'Spanisch',
            'ar' => 'Arabisch',
            'ja_JP' => 'Japanisch',
            'it_IT' => 'Italienisch',
            'en_GB' => 'Englisch (International)',
            'en_US' => 'Englisch (Vereinigte Staaten)',
        ],
        'es_ES' => [
            'auto' => 'Usar idioma del perfil de WordPress',
            'pt_BR' => 'Portugués (Brasil)',
            'pt_PT' => 'Portugués',
            'fr_FR' => 'Francés',
            'de_DE' => 'Alemán',
            'es_ES' => 'Español',
            'ar' => 'Árabe',
            'ja_JP' => 'Japonés',
            'it_IT' => 'Italiano',
            'en_GB' => 'Inglés (Internacional)',
            'en_US' => 'Inglés (Estados Unidos)',
        ],
        'ar' => [
            'auto' => 'استخدام لغة ملف WordPress الشخصي',
            'pt_BR' => 'البرتغالية (البرازيل)',
            'pt_PT' => 'البرتغالية',
            'fr_FR' => 'الفرنسية',
            'de_DE' => 'الألمانية',
            'es_ES' => 'الإسبانية',
            'ar' => 'العربية',
            'ja_JP' => 'اليابانية',
            'it_IT' => 'الإيطالية',
            'en_GB' => 'الإنجليزية (دولي)',
            'en_US' => 'الإنجليزية (الولايات المتحدة)',
        ],
        'ja_JP' => [
            'auto' => 'WordPressプロフィールの言語を使用',
            'pt_BR' => 'ポルトガル語（ブラジル）',
            'pt_PT' => 'ポルトガル語',
            'fr_FR' => 'フランス語',
            'de_DE' => 'ドイツ語',
            'es_ES' => 'スペイン語',
            'ar' => 'アラビア語',
            'ja_JP' => '日本語',
            'it_IT' => 'イタリア語',
            'en_GB' => '英語（国際）',
            'en_US' => '英語（アメリカ）',
        ],
    ];
}

/**
 * Resolve which locale should drive settings-tab UI copy.
 */
function breakdance_languages_resolve_settings_ui_locale(?string $preference = null): string
{
    $catalog = breakdance_languages_settings_ui_catalog();

    if ($preference === null || $preference === '') {
        $preference = breakdance_languages_get_user_builder_locale();
    }

    if ($preference === BREAKDANCE_LANGUAGES_AUTO_LOCALE) {
        $resolved = breakdance_languages_match_supported_locale(breakdance_languages_get_unfiltered_user_locale());

        return $resolved && isset($catalog[$resolved]) ? $resolved : 'en_US';
    }

    if (isset($catalog[$preference])) {
        return $preference;
    }

    $matched = breakdance_languages_match_supported_locale($preference);

    if ($matched !== null && isset($catalog[$matched])) {
        return $matched;
    }

    return 'en_US';
}

/**
 * Get settings-tab UI strings for a locale preference or code.
 *
 * @return array{loading:string,ready:string,success:string,error:string,refresh:string}
 */
function breakdance_languages_get_settings_ui_strings(?string $preference = null): array
{
    $catalog = breakdance_languages_settings_ui_catalog();
    $labels_catalog = breakdance_languages_locale_labels_catalog();
    $locale = breakdance_languages_resolve_settings_ui_locale($preference);
    $strings = array_merge($catalog['en_US'], $catalog[$locale] ?? []);
    $native_labels = $labels_catalog[$locale] ?? $labels_catalog['en_US'];
    $supported_labels = breakdance_languages_supported_locales();
    $strings['locale_labels'] = array_merge($supported_labels, $native_labels);
    $strings['locale_labels']['auto'] = $native_labels['auto'] ?? $labels_catalog['en_US']['auto'];

    return $strings;
}

/**
 * Build a locale => strings map for the settings tab script.
 *
 * @return array<string, array{loading:string,ready:string,success:string,error:string,refresh:string}>
 */
function breakdance_languages_get_settings_ui_strings_by_locale(): array
{
    $map = [];

    foreach (breakdance_languages_supported_locale_codes() as $locale) {
        $map[$locale] = breakdance_languages_get_settings_ui_strings($locale);
    }

    $map[BREAKDANCE_LANGUAGES_AUTO_LOCALE] = breakdance_languages_get_settings_ui_strings(
        BREAKDANCE_LANGUAGES_AUTO_LOCALE
    );

    return $map;
}
